replicaCount: 3
image:
  repository: flask-hello-world
  tag: latest
  pullPolicy: IfNotPresent
  imageCredentials:
#    registry: <repo>
#    username: <username>
#    password: <pw>
service:
  protocol: HTTP
  port: 80
  type: NodePort
serviceAccount:
  create: no
ingress:
  enabled: yes
  type: ClusterIp
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels: { }
  path: /
  hosts:
    - name: localhost
      paths:
        - fullName: helm-flask-hello-world
          svcPort: 80
autoscaling:
  enabled: no